---
- name: Install language
  dnf:
    name: go
    state: latest
  become: yes

- name: Config folder
  ansible.builtin.file:
    mode: "0755"
    path: "{{ ansible_user_dir }}/Development/language/go"
    state: directory
